import type {Metadata} from 'next';
import './globals.css';
import '../../public/assets/fonts/fonts.css';
import ReactQueryProvider from '@/contexts/ReactQueryProvider';
import AuthProvider from '@/contexts/AuthProvider';
import {AxiosInterceptor} from '@/hooks/useAxiosInterceptor';
import MainLayout from '@/components/MainLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <ReactQueryProvider>
          <AxiosInterceptor>
            {/*<AuthProvider>*/}
            <MainLayout>{children}</MainLayout>
            {/*</AuthProvider>*/}
          </AxiosInterceptor>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
